# Generated by Django 4.2.16 on 2025-11-30 14:49
from django.db import migrations


def seed_data(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Role = apps.get_model('users', 'Role')
    Permission = apps.get_model('users', 'Permission')
    RolePermission = apps.get_model('users', 'RolePermission')
    UserRole = apps.get_model('users', 'UserRole')

    admin_role = Role.objects.create(name='admin')
    manager_role = Role.objects.create(name='manager')
    user_role = Role.objects.create(name='user')

    users_view = Permission.objects.create(code='users.view')
    users_edit = Permission.objects.create(code='users.edit')
    users_delete = Permission.objects.create(code='users.delete')
    users_list = Permission.objects.create(code='users.list')
    objects_view = Permission.objects.create(code='objects.view')
    objects_edit = Permission.objects.create(code='objects.edit')
    objects_delete = Permission.objects.create(code='objects.delete')

    RolePermission.objects.create(role=admin_role, permission=users_view)
    RolePermission.objects.create(role=admin_role, permission=users_edit)
    RolePermission.objects.create(role=admin_role, permission=users_delete)
    RolePermission.objects.create(role=admin_role, permission=users_list)
    RolePermission.objects.create(role=admin_role, permission=objects_view)
    RolePermission.objects.create(role=admin_role, permission=objects_edit)
    RolePermission.objects.create(role=admin_role, permission=objects_delete)
    RolePermission.objects.create(role=manager_role, permission=users_view)
    RolePermission.objects.create(role=manager_role, permission=users_list)
    RolePermission.objects.create(role=manager_role, permission=objects_view)
    RolePermission.objects.create(role=manager_role, permission=objects_delete)
    RolePermission.objects.create(role=user_role, permission=objects_view)

    admin_user = User.objects.get(email='geney@gmail.com')
    UserRole.objects.create(user=admin_user,role=admin_role)

    manager_user = User.objects.get(email='test@mail.com')
    UserRole.objects.create(user=manager_user, role=manager_role)

class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data)
    ]