# Generated by Django 4.2.16 on 2025-11-30 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_permission_role_alter_user_id_userrole_and_more'),
        ('users', '0003_seed_roles_permissions'),
    ]

    operations = [
    ]
