# Generated by Django 4.2.16 on 2025-12-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20251130_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
