# Generated by Django 4.2.16 on 2025-12-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_source_field'),
        ('users', '0006_seed_roles_permissions_v2'),
    ]

    operations = [
    ]
