# Generated by Django 4.2.16 on 2025-12-08 11:31

from django.db import migrations

def add_null_role(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    Role.objects.get_or_create(name='null', source='migration_0008')

def reverse_add(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    Role.objects.filter(source='migration_0008').delete()



class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20251207_1309'),
    ]

    operations = [
        migrations.RunPython(add_null_role, reverse_add)
    ]
